<?php

$preamp_config['custom_post_type']['slider'] = array(
	'active' => true,
	'labels' => array(
		'name'               => _x( 'Slider', 'post type general name', 'copernicus-prime' ),
		'singular_name'      => _x( 'Slider', 'post type singular name', 'copernicus-prime' ),
		'menu_name'          => _x( 'Slider', 'admin menu', 'copernicus-prime' ),
		'name_admin_bar'     => _x( 'Slider', 'add new on admin bar', 'copernicus-prime' ),
		'add_new'            => _x( 'Add New', 'add new', 'copernicus-prime' ),
		'add_new_item'       => __( 'Add New Slide', 'copernicus-prime' ),
		'new_item'           => __( 'New Slide', 'copernicus-prime' ),
		'edit_item'          => __( 'Edit Slide', 'copernicus-prime' ),
		'view_item'          => __( 'View Slide', 'copernicus-prime' ),
		'all_items'          => __( 'All Slides', 'copernicus-prime' ),
		'search_items'       => __( 'Search Slide', 'copernicus-prime' ),
		'parent_item_colon'  => __( 'Parent Slide:', 'copernicus-prime' ),
		'not_found'          => __( 'No Slide found.', 'copernicus-prime' ),
		'not_found_in_trash' => __( 'No Slides found in Trash.', 'copernicus-prime' ),
	),
	'description' => __( 'Description.', 'copernicus-prime' ),
	'public' => false,
	'hierarchical' => false,
	'exclude_from_search' => true,
	'publicly_queryable' => false,
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'menu_position' => null,
	'menu_icon' => 'dashicons-admin-post',
	'capability_type' => 'post',
	// 'capabilities' => array('edit_posts'),
	// 'map_meta_cap' => false,
	'supports' => array( 'title', 'editor', 'thumbnail' ), // 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments'
	// 'register_meta_box_cb' => true,
	// 'taxonomies' => array(),
	// 'has_archive' => false,
	'rewrite' => array( 'slug' => 'slide' ),
	'query_var' => true,
	'can_export' => true,
	'delete_with_user' => true,
);
